// <auto-generated />
namespace ASP.ExamTask_v1._1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GradeRange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GradeRange));
        
        string IMigrationMetadata.Id
        {
            get { return "202302202138252_GradeRange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
